# Generated by Django 6.0.3 on 2026-03-13 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('duracao_consulta', models.PositiveIntegerField(default=20, help_text='Duração da consulta em minutos')),
                ('vagas_particular', models.PositiveIntegerField(default=0)),
                ('vagas_convenio', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='medicos.medico')),
            ],
            options={
                'verbose_name': 'Agenda do Médico',
                'verbose_name_plural': 'Agendas dos Médicos',
                'ordering': ['medico__nome', 'dia_semana', 'hora_inicio'],
            },
        ),
    ]
