# Generated by Django 6.0.3 on 2026-03-13 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0002_agendamedico'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atendimento', models.CharField(choices=[('particular', 'Particular'), ('convenio', 'Convênio')], max_length=20)),
                ('data_consulta', models.DateField()),
                ('hora_consulta', models.TimeField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('aguardando', 'Aguardando'), ('em_atendimento', 'Em atendimento'), ('finalizado', 'Finalizado'), ('faltou', 'Faltou'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='medicos.convenio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='medicos.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data_consulta', 'hora_consulta'],
                'constraints': [models.UniqueConstraint(fields=('medico', 'data_consulta', 'hora_consulta'), name='unique_agendamento_medico_data_hora')],
            },
        ),
    ]
