# Generated by Django 6.0.3 on 2026-03-14 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0002_agendamedico'),
        ('pacientes', '0002_alter_paciente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Guichê',
                'verbose_name_plural': 'Guichês',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SenhaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo_prioridade', models.CharField(choices=[('preferencial', 'Preferencial'), ('normal', 'Normal')], max_length=20)),
                ('tipo_atendimento', models.CharField(choices=[('particular', 'Particular'), ('convenio', 'Convênio')], max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('data_emissao', models.DateField()),
                ('hora_emissao', models.TimeField()),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('chamada', 'Chamada'), ('em_atendimento', 'Em atendimento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aguardando', max_length=20)),
            ],
            options={
                'verbose_name': 'Senha de Atendimento',
                'verbose_name_plural': 'Senhas de Atendimento',
                'ordering': ['-data_emissao', '-hora_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ChamadaSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_chamada', models.DateTimeField(auto_now_add=True)),
                ('guiche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamadas', to='recepcao.guiche')),
                ('senha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='recepcao.senhaatendimento')),
            ],
            options={
                'verbose_name': 'Chamada de Senha',
                'verbose_name_plural': 'Chamadas de Senha',
                'ordering': ['-hora_chamada'],
            },
        ),
        migrations.CreateModel(
            name='AtendimentoGuiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_guiche', to='medicos.convenio')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_guiche', to='pacientes.paciente')),
                ('guiche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='recepcao.guiche')),
                ('senha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento_guiche', to='recepcao.senhaatendimento')),
            ],
            options={
                'verbose_name': 'Atendimento no Guichê',
                'verbose_name_plural': 'Atendimentos no Guichê',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
